server:
  port: 8020

spring:
  application:
    name: SCC-SERVER

#   数据库配置
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    #   redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      timeout : 6000ms

#   mybatis配置
    mybatis:
      mapper-locations: classpath*:mapper/*.xml
      typeAliasesPackage: scc.server.dao.po

#   自定义配置(开启则做登陆校验，方便测试)
    scc:
      login-check-enabled: true